# Generated by Django 5.0.6 on 2024-06-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diripe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shiiregyosya',
            fields=[
                ('shiireid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('shiiremei', models.CharField(max_length=64)),
                ('shiireaddress', models.CharField(max_length=64)),
                ('shiiretel', models.CharField(max_length=13)),
                ('shihonkin', models.IntegerField()),
                ('nouki', models.IntegerField()),
            ],
        ),
    ]
