# Generated by Django 5.0.6 on 2024-07-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diripe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='medicineid',
            new_name='medicinename',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='date',
            field=models.DateField(),
        ),
    ]
