# Generated by Django 5.0.6 on 2024-07-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diripe', '0002_rename_medicineid_treatment_medicinename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='medicinename',
            field=models.CharField(max_length=64),
        ),
    ]
