# Generated by Django 5.0.6 on 2024-06-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diripe', '0005_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patid', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('impdate', models.DateField()),
                ('medicineid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='Diripe.medicine')),
            ],
        ),
        migrations.DeleteModel(
            name='prescription',
        ),
    ]
